CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'CREATOR',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS earnings (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  creator_name VARCHAR(255),
  creator_email VARCHAR(255),
  platform VARCHAR(100),
  period VARCHAR(50),
  amount NUMERIC(10, 2) NOT NULL,
  currency VARCHAR(10) DEFAULT 'NGN',
  status VARCHAR(50) DEFAULT 'VERIFIED',
  payment_status VARCHAR(50) DEFAULT 'UNPAID',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loans (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  creator_name VARCHAR(255),
  creator_email VARCHAR(255),
  requested_amount NUMERIC(10, 2) NOT NULL,
  interest NUMERIC(10, 2) NOT NULL,
  remaining_balance NUMERIC(10, 2) NOT NULL,
  status VARCHAR(50) DEFAULT 'PENDING',
  request_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS monetization (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  creator_name VARCHAR(255),
  creator_email VARCHAR(255),
  platform VARCHAR(100) NOT NULL,
  handle VARCHAR(255),
  current_followers INTEGER DEFAULT 0,
  status VARCHAR(50) DEFAULT 'IN_REVIEW',
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoices (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  invoice_number VARCHAR(100) UNIQUE NOT NULL,
  issue_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  period VARCHAR(50),
  amount NUMERIC(10, 2) NOT NULL,
  status VARCHAR(50) DEFAULT 'UNPAID'
);
